Lab 5
Bazalii/Web pull request #11
Opened 2022-11-14 12:34 UTC by Bazalii

Closes #6

2022-11-14 13:35 UTC, BakasaRus requested changes
1. Было бы неплохо сохранять таблицу при добавлении элемента и загружать её сразу после загрузки страницы
2. Хочу, чтобы работал Enter в полях ввода...

2022-11-14 13:35 UTC, BakasaRus commented on js/dynamicTable.js
> +    let rowsNumber = Number(rows);
Нужна валидация хотя бы на предмет того, что там есть что-то адекватное, в идеале нужно поменять тип полей

2022-11-14 13:35 UTC, BakasaRus commented on js/dynamicTable.js
> +    }
Вот тут бы хорошо выглядел `repeat()`

2022-11-14 13:35 UTC, BakasaRus commented on js/dynamicTable.js
> +    cell.style.textAlign = 'center';
Вот это лучше делать через CSS, а не тут

2022-11-14 13:35 UTC, BakasaRus commented on js/dynamicTable.js
> +function loadTable() {
Вот это надо бы отрефакторить так, чтобы не дублировалось создание разметки под таблицу

![говно-переделывай](https://user-images.githubusercontent.com/21131366/201672285-1d6870e6-b031-4e8d-b11d-810484a7a9c7.gif)

2022-11-14 13:35 UTC, BakasaRus commented on js/dynamicTable.js
> +            };
Почему нельзя хранить двумерный массив...

2022-11-15 18:11 UTC, Bazalii commented on js/dynamicTable.js
> +    let rowsNumber = Number(rows);
Fixed

2022-11-15 18:16 UTC, Bazalii commented on js/dynamicTable.js
> +    cell.style.textAlign = 'center';
Fixed

2022-11-15 18:40 UTC, Bazalii commented on js/dynamicTable.js
> +    }
Fixed

2022-11-15 18:49 UTC, Bazalii commented on js/dynamicTable.js
> +            };
Потому что сохраняется информация только о непустых ячейках

2022-11-15 19:44 UTC, Bazalii commented on js/dynamicTable.js
> +function loadTable() {
Fixed

2022-11-21 11:51 UTC, BakasaRus commented on js/dynamicTable.js
> +    }
![говно-переделывай](https://user-images.githubusercontent.com/21131366/201672285-1d6870e6-b031-4e8d-b11d-810484a7a9c7.gif)

2022-11-21 11:52 UTC, BakasaRus commented on js/dynamicTable.js
> +    }
Надо было использовать `repeat()` из CSS, а не из JS...

2022-11-21 11:57 UTC, BakasaRus requested changes
Надо сделать так, чтобы обрабатывалось событие отправки формы, чтобы работала дефолтная валидация формы, и подавлять перезагрузку с помощью [`preventDefault()`](https://developer.mozilla.org/ru/docs/Web/API/Event/preventDefault)

2022-11-21 11:57 UTC, BakasaRus commented on js/dynamicTable.js
> +    let gridTemplateColumns = 'minmax(100px, 250px)'.repeat(columnsNumber);
``repeat(${columnNumbers}, minmax(100px, 250px))``

2022-11-21 12:04 UTC, Bazalii commented on js/dynamicTable.js
> +    let gridTemplateColumns = 'minmax(100px, 250px)'.repeat(columnsNumber);
Fixed

2022-11-21 12:04 UTC, Bazalii commented on js/dynamicTable.js
> +    }
Fixed

2022-11-21 12:44 UTC, BakasaRus approved these changes

2022-11-21 13:48 UTC, merged