Lab 6
Bazalii/Web pull request #12
Opened 2022-12-05 10:17 UTC by Bazalii

- Closes #7

2022-12-05 12:31 UTC, BakasaRus requested changes

2022-12-05 12:31 UTC, BakasaRus commented on js/workReviews.js
> +            </div>
В `<template/>`

2022-12-05 12:31 UTC, BakasaRus commented on js/workReviews.js
> +    let response = await fetch(`https://jsonplaceholder.typicode.com/posts/${randomNumber}/comments`);
Если у тебя в целом нет ответа от сервера, то метод кидает исключение, которое нужно ловить и показывать сообщение об ошибке на странице

2022-12-05 13:04 UTC, Bazalii commented on js/workReviews.js
> +    let response = await fetch(`https://jsonplaceholder.typicode.com/posts/${randomNumber}/comments`);
Fixed

2022-12-05 19:05 UTC, Bazalii commented on js/workReviews.js
> +            </div>
Fixed

2022-12-29 22:56 UTC, BakasaRus approved these changes

2022-12-30 07:14 UTC, merged