Lab 2
Bazalii/Web pull request #8
Opened 2022-09-23 20:20 UTC by Bazalii

CLoses #3

2022-09-26 11:21 UTC, BakasaRus requested changes
1. Не хватает `text-style` (стилизация текста)
2. Не хватает зачёркиваний, подчёркиваний и т.д.

2022-09-26 11:21 UTC, BakasaRus commented on css/mainTags.css
> +}
Можно эти стили вешать на сам элемент, а не на класс

2022-09-26 11:21 UTC, BakasaRus commented on css/mainTags.css
> +}
Можно переписать селекторы так, чтобы выбирались только те `<header/>` и пр., которые лежат непосредственно внутри `<body/>`

2022-09-26 11:21 UTC, BakasaRus commented on Projects.html
>          </ul>
Можно стилизовать все ссылки, которые лежат внутри списка с заданным классом

2022-09-26 11:21 UTC, BakasaRus commented on Projects.html
>      </nav>
См. ниже

2022-09-26 11:21 UTC, BakasaRus commented on css/text.css
> +    font-family: serif;
Посмотреть, что за шрифт `serif` и аналогичные, заменить на конкретные шрифты из Google Fonts

2022-09-26 11:21 UTC, BakasaRus commented on css/text.css
> +    white-space: normal;
Тут лучше поиграться с `letter-spacing`

2022-09-26 11:29 UTC, Bazalii commented on css/mainTags.css
> +}
Fixed

2022-09-26 11:29 UTC, Bazalii commented on css/mainTags.css
> +}
Fixed

2022-09-26 11:30 UTC, Bazalii commented on Projects.html
>          </ul>
Fixed

2022-09-26 11:39 UTC, Bazalii commented on Projects.html
>      </nav>
Fixed

2022-09-26 11:49 UTC, Bazalii commented on css/text.css
> +    white-space: normal;
Fixed

2022-09-26 11:54 UTC, Bazalii commented on css/text.css
> +    font-family: serif;
Fixed

2022-10-09 18:46 UTC, BakasaRus commented on Projects.html
>          </ul>
Вообще, планировалось, что ты напишешь сложный селектор, который как раз выберет элементы по условию, которое я описал. Можно же, например, в шапке/подвале красить ссылки одним цветом, а в списках другим

2022-10-09 19:13 UTC, Bazalii commented on Projects.html
>          </ul>
Fixed

2022-10-10 12:57 UTC, BakasaRus approved these changes

2022-10-10 13:07 UTC, merged